version: "3.8"

services:
    retext:
        build:
            context: .
            args:
                - USER=retext
            dockerfile: Dockerfile.dev
        container_name: retext
        tty: true
        user: retext
        volumes:
            - $HOME/.ssh:/home/memotion_app/.ssh
            - ../..:/workspace:cached
