[package]
name = "adapter"
version = "0.1.0"
authors = ["Kawano Kenichi <bppk28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

application = { path = "../application" }
actix-web = "3.3.2"
serde = "1"
