apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ssc-retext
  name: ssc-retext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ssc-retext
  template:
    metadata:
      labels:
        name: ssc-retext
    spec:
      containers:
        - name: ssc-retext
          image: ssc_retext:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
